(load "accumulate.scm")
(define (count-leaves t)
    (accumulate + 0 (map (lambda (sub-tree)
                             (if (pair? sub-tree)
                                 (count-leaves sub-tree)
                                 1))
                     t)))
