(load "set-as-tree.scm")
(define tree1 '())
(define tree1 (adjoin-set 7 tree1))
(define tree1 (adjoin-set 3 tree1))
(define tree1 (adjoin-set 9 tree1))
(define tree1 (adjoin-set 1 tree1))
(define tree1 (adjoin-set 5 tree1))
(define tree1 (adjoin-set 11 tree1))

(define tree2 '())
(define tree2 (adjoin-set 3 tree2))
(define tree2 (adjoin-set 1 tree2))
(define tree2 (adjoin-set 7 tree2))
(define tree2 (adjoin-set 5 tree2))
(define tree2 (adjoin-set 9 tree2))
(define tree2 (adjoin-set 11 tree2))

(define tree3 '())
(define tree3 (adjoin-set 5 tree3))
(define tree3 (adjoin-set 3 tree3))
(define tree3 (adjoin-set 1 tree3))
(define tree3 (adjoin-set 9 tree3))
(define tree3 (adjoin-set 7 tree3))
(define tree3 (adjoin-set 11 tree3))

