(load "tag-content.scm")
(define (install-polar-package)
    (define (square x) (* x x))
    (define (mymagnitude z) (car z))
    (define (myang z) (cdr z))
    (define (make-from-mag-ang m z) (cons m z))
    (define (myreal-part z)
        (* (mymagnitude z) (cos (myang z))))
    (define (myimag-part z)
        (* (mymagnitude z) (sin (myang z))))
    (define (make-from-real-imag x y)
        (cons (sqrt (+ (square x) (square y)))
              (atan y x)))

    (define (tag x) (attach-tag 'polar x))
    (put 'real-part '(polar) myreal-part)
    (put 'imag-part '(polar) myimag-part)
    (put 'magnitude '(polar) mymagnitude)
    (put 'angle '(polar) myang)
    (put 'make-from-real-img 'polar (lambda (x y) 
					     (tag (make-from-real-imag x y))))
    (put 'make-from-mag-ang 'polar (lambda (r a)
  					     (tag (make-from-mag-ang r a))))
    'done)
