(define (make-account balance password)
    (define (withdraw amount)
        (if (>= balance amount)
            (begin (set! balance (- balance amount))
		   balance)
	    "Insufficient funds"))
    (define (desposit amount)
        (set! balance (+ balance amount))
	balance)
    (define (correct-password? pas)
        (eq? pas password))
    (define (display-wrong-passw-message useless)
        (display "Incorrect password"))
    (define (dispatch passw m)
        (if (correct-password? passw)
	    (begin (cond ((eq? m 'withdraw) withdraw)
			 ((eq? m 'desposit) desposit)
                         (else (error "Unknown request--MAKE-ACCOUNT" m))))
            display-wrong-passw-message))
    dispatch)
