(define (make-account balance password)
    (define (withdraw amount)
        (if (>= balance amount)
            (begin (set! balance (- balance amount))
		   balance)
	    "Insufficient funds"))
    (define (desposit amount)
        (set! balance (+ balance amount))
	balance)
    (define (correct-password? pas)
        (eq? pas password))
    (define (display-wrong-passw-message useless)
        (display "Incorrect password"))
    (define (call-the-cops useless)
        (display "Calling the cops..."))
    (let ((uncorrent-count 0))
         (define (dispatch passw m)
            (if (correct-password? passw)
	        (begin (set! uncorrent-count 0)
                             (cond ((eq? m 'withdraw) withdraw)
		             ((eq? m 'desposit) desposit)
                             (else (error "Unknown request--MAKE-ACCOUNT" m))))
                (begin (set! uncorrent-count (+ uncorrent-count 1)) 
                       (if (>= uncorrent-count 3)
                           call-the-cops
                           display-wrong-passw-message))))
          dispatch))
